server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 1. Servire i file statici Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Inoltrare le chiamate API all'API Gateway dentro la rete Docker
    location /iam-service/ {
        proxy_pass http://api-gateway:8080/iam-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /support-service/ {
        proxy_pass http://api-gateway:8080/support-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /dss-service/ {
        proxy_pass http://api-gateway:8080/dss-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}